
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: scharwerk_development
  pool: 15
  timeout: 5000
  password:
  
test:
  <<: *default
  database: scharwerk_test
  pool: 15
  timeout: 5000
  password:
  
production:
  <<: *default
  database: scharwerk_production
  username: rails
  host: localhost
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
