# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 604ec09a05cfab8a47934e8ff9edd84973e838885a6f1f31b0cd90b7e0326fe7585412752f03a12e96c3f96ab934dac0e219fa944cba3c005f63e1e90f772da4

test:
  secret_key_base: 3f39abbfaa22ac7fd85fbc7be2472348151bfd1a1e444dc2197b4876a13f168ee0ca03ed2abc1774253f134690068e83fc107968912811385d6548c92f2099be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
